### ISSUE TITLE
Issue with build for D70771 (244908): Apply the already landed patch

### ISSUE THREAD

**Issue by qshanz373** [google/llvm-premerge-checks#131] opened 2020-02-17 02:57 UTC
**Describe the bug**
If the dependent patch has already been landed, the pre-merge check still try to apply that patch which cause the build failure. For now, I have to remove the parent revision.
Relevant links:
https://reviews.llvm.org/harbormaster/build/49158/
**To Reproduce**
1. Submit
2. 

**Expected behavior**

**Screenshots**

**Comment by ChristianKuehnel** [comment] 2020-02-17 07:47
I guess this is a duplicate of #72

**Comment by ChristianKuehnel** [comment] 2020-04-30 09:34
closing duplicate

**Closed by ChristianKuehnel** 2020-04-30 09:34 UTC
Labels: bug
