### ISSUE TITLE
Report which change caused master failure

### ISSUE THREAD

**Issue by metaflow** [google/llvm-premerge-checks#111] opened 2020-01-24 14:08 UTC
It would be nice if agent will be able to tell which commit of many caused breakage of master build.

**Comment by njames93** [comment] 2020-01-24 17:13
This isn't really to do with pre-merge checks though is it. Also isn't that what the blame list is for?

**Comment by metaflow** [comment] 2020-01-24 20:54
@njames93 
> This isn't really to do with pre-merge checks though is it. Also isn't that what the blame list is for?
Yes, it's not about the pre-merge checks. I was thinking about not reporting test failures that are caused by failures on master.
I am not familiar with "blame list", what is that?

**Comment by njames93** [comment] 2020-01-25 13:05
> @njames93
> 
> > This isn't really to do with pre-merge checks though is it. Also isn't that what the blame list is for?
> 
> Yes, it's not about the pre-merge checks. I was thinking about not reporting test failures that are caused by failures on master.
> I am not familiar with "blame list", what is that?
I mean when an llvm build fails and it emails everyone who has committed since the last successful build

**Comment by ChristianKuehnel** [comment] 2020-01-27 07:57
I suppose this is a duplicate of #9

**Closed by ChristianKuehnel** 2020-01-27 07:57 UTC
Labels: enhancement
