### ISSUE TITLE
Spurious test failure in check-cxx

### ISSUE THREAD

**Issue by androm3da** [google/llvm-premerge-checks#138] opened 2020-02-25 18:27 UTC
**Spurious test failure in check-cxx**
https://reviews.llvm.org/D75085 "NFCI" change to llvm libsupport, resulted in https://reviews.llvm.org/harbormaster/unit/view/3980/ libcxx failure:

```
Command: ['/mnt/disks/ssd0/agent/workspace/amd64_debian_testing_clang8/build/projects/libcxx/test/std/thread/thread.mutex/thread.mutex.requirements/thread.mutex.requirements.mutex/thread.mutex.class/Output/try_lock.pass.cpp.exe']
Exit Code: -6
Standard Error:
--
try_lock.pass.cpp.exe: /mnt/disks/ssd0/agent/workspace/amd64_debian_testing_clang8/libcxx/test/std/thread/thread.mutex/thread.mutex.requirements/thread.mutex.requirements.mutex/thread.mutex.class/try_lock.pass.cpp:43: void f(): Assertion `d < ms(200)' failed.
--

Compiled test failed unexpectedly!
```

llvm-dev / libcxx-dev post was created in order to facilitate discussion http://lists.llvm.org/pipermail/llvm-dev/2020-February/139476.html

**Comment by njames93** [comment] 2020-02-26 16:00
It was just an issue on master, I restarted the build and the failure went away. These happen often. Theres not an easy way to detect these apart from maybe building and running tests on trunk, then applying the patch and re running the tests, see if there is a difference in the output(but thats a lot of extra computation)

**Comment by ChristianKuehnel** [comment] 2020-02-26 17:24
Then I'm closing this as duplicate of #9

**Closed by ChristianKuehnel** 2020-02-26 17:24 UTC
Labels: bug

**Comment by androm3da** [comment] 2020-02-26 20:57
I think it would be valuable to have a way to re-trigger a build with the same patch.  And/or a link to the `llvm-premerge-checks` docs on how to investigate or resolve test failures.

Yes, I realize that the test failure doesn't block changes under review from being merged.  But I think there should be a process for folks to follow who want to color within the lines.  :)

Do you think a doc change is feasible -- should I open a new issue?

**Comment by ChristianKuehnel** [comment] 2020-02-26 21:02
You should be able to "run build manually" in Harbormaster:
https://reviews.llvm.org/harbormaster/plan/4/
